server:
  port: 6868

# Eureka Server
eureka:
  client:
    # \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D, default: true (\u672C\u8EAB\u5C31\u662FEureka\u670D\u52A1, \u65E0\u987B\u6CE8\u518C)
    register-with-eureka: false
    # \u662F\u5426\u4ECEEureka\u4E2D\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F, default: true
    fetch-registry: false
    # Eureka client \u4E0E server \u4EA4\u4E92\u5730\u5740
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

  server:
    # \u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F(\u56E0\u7F51\u7EDC\u9020\u6210\u8D85\u8FC790\u79D2\u65E0\u5FC3\u8DF3\u800C\u6CE8\u9500\u670D\u52A1\u6CE8\u518C\u8868\u4E2D\u7684\u5FAE\u670D\u52A1) default: true(\u5F00\u542F: \u4E0D\u76F2\u76EE\u6CE8\u9500\u4EFB\u4F55\u5FAE\u670D\u52A1)
    enable-self-preservation: true

# \u5B89\u5168\u8BA4\u8BC1
security:
  # \u57FA\u4E8E HTTP basic \u8BA4\u8BC1
  basic:
    enabled: true
  user:
    name: administrator
    password: omega