server:
  # 运行时, 指定参数, 通过入口函数: --port=?或JVM: -Dport=?传递
  port: ${port:7777}

# Eureka Server 单节点
eureka:
  client:
    # 是否将自己注册到Eureka服务中, false(单节点)
    register-with-eureka: false
    # 是否从Eureka中获取注册信息, false(单节点)
    fetch-registry: false

  server:
    # 自我保护模式(因网络造成超过90秒无心跳而注销服务注册表中的微服务) default: true(开启: 不盲目注销任何微服务)
    enable-self-preservation: true

# 安全认证
security:
  # 基于 HTTP basic 认证
  basic:
    enabled: true
  user:
    name: administrator
    password: omega